package com.example.myapplication2_

// The User class in Kotlin with the same properties and methods as in Java
data class User(
    var username: String,
    var password: String
)

class UserActivity {

    // Example usage of the User class
    fun exampleUsage() {
        // Creating a user object
        val user = User(username = "john_doe", password = "1234")

        // Accessing properties using getter methods (automatically generated by Kotlin)
        println("Username: ${user.username}")
        println("Password: ${user.password}")

        // Updating user properties using setter methods
        user.username = "new_username"
        user.password = "new_password"

        // Display the updated values
        println("Updated Username: ${user.username}")
        println("Updated Password: ${user.password}")
    }
}
